### ISSUE TITLE
Plex docker on unraid

### ISSUE THREAD

**Issue by GilbN** [unclenoriega/Lazyman.bundle#6]
I have tried to get this to work on my unriad system using, the the lsio plex docker. But the streams are just spinning forever when I try with plex web. If I try on my nvidia shield I get an error that says I need to restart the app or plex server. 
I have edited the host file to `176.9.99.173 mf.svc.nhl.com`  But it still wont work. And when I check the host file inside the container it  also contains `176.9.99.173 mf.svc.nhl.com` 

Do you have any ideas?

**Comment by unclenoriega** [comment]
There were some errors that were just fixed last night. Make sure you try the newest version.

**Comment by GilbN** [comment]
Seem to work with the latest build! Thank you!
